### ISSUE TITLE
Możliwość nieustawienia linku do fazy/meczu

### ISSUE THREAD

**Issue by michzimny** [emkael/jfrteamy-playoff#13]
Np. "V zjazd" na wielu stronach prowadzi teraz do "#". Czy można by zrobić ładniej w ten sposób, że jeśli link nie jest podany, to link się nie generuje w html, tj. nie prowadzi ani do "#" ani do "", tylko po prostu dany tekst nie jest wtedy linkiem?

**Comment by emkael** [comment]
Pewnie siędasię.
Tylko nagłówki, czy linki do meczów również?

**Comment by michzimny** [comment]
Chyba też UX byłoby, gdyby nieklikalny link był nieklikalny :)
