### ISSUE TITLE
Pozwolić wyeksportować definicję tabelki na jakiś URL

### ISSUE THREAD

**Issue by michzimny** [emkael/jfrteamy-playoff#2]
W lokalnym jsonie wystarczą dane dostępowe do MySQL, ścieżka do pliku wynikowego itp.

Natomiast zamiast definiować tabelkę play-off lokalnie, można by podać URL do zdalnego JSON-a, który przy każdym odpaleniu programu byłby pobierany.

Use case: sędzia główny IT lig centralnych zarządzający pozostałymi komputerowcami.

**Comment by emkael** [comment]
Może sekcja lokalnego JSONa (np. `remotes`) zawierająca tablicę URL, z których pobierane są piki JSON, które są scalane do konfiguracji lokalnej, w kolejności zdefiniowania.

W ten sposób w ogóle można zmodularyzować definicje poszczególnych sekcji konfiguracji.

**Comment by michzimny** [comment]
Tak. Tylko, że jak ktoś lokalnie dany klucz zdefiniuje, to remotes mu danego klucza już nie nadpisują.

Np. jak sędzia sobie zdefiniuje klucz phases mimo klucza remotes, to znaczy, że ignoruje sędziego głównego.

**Comment by emkael** [comment]
Ok. Per sekcja wystarczy, czy scalanie jakieś inteligentniejsze scalanie głębiej jest niezbędne?

**Comment by michzimny** [comment]
Myślę, że per sekcja, tj. płytko. Inaczej to by chyba trzeba było analizować semantykę poszczególnych części drzewa, żeby sensownie scalać.

**Comment by emkael** [comment]
> jak ktoś lokalnie dany klucz zdefiniuje, to remotes mu danego klucza już nie nadpisują

A jeśli kilka remotes ma ten sam klucz - bierzemy ostatni (czyli nadpisują) czy pierwszy (czyli nie)?

**Comment by emkael** [comment]
Uznałem, że nadpisują. Możemy chcieć np. konkretnemu kotłowi zdefiniować inne parametry niż wszystkim, wówczas modularność plików nam na to pozwala.
