### ISSUE TITLE
Oznaczanie miejsc awansowych/spadkowych w klasyfikacji końcowej

### ISSUE THREAD

**Issue by emkael** [emkael/jfrteamy-playoff#23]
Dodawanie klasy `.winner` i `.loser` dla zdefiniowanych w konfiguracji miejsc klasyfikacji końcowej.

Przydatne w lidze.

**Comment by michzimny** [comment]
Nazwałbym klasy jakoś inaczej, bo te za bardzo kojarzą się z wynikiem
meczu. Może promotion i coś... drop?

niedz., 15.04.2018, 12:56 użytkownik Michał Klichowicz <
notifications@github.com> napisał:
