### ISSUE TITLE
Parametryzacja skracania nazw teamów

### ISSUE THREAD

**Issue by emkael** [emkael/jfrteamy-playoff#27]
9a42b9f w gałęzi rozwojowej wprowadziło skracanie długich nazw teamów (wierszy tabeli docelowej) - żeby długie nazwy i/lub łańcuchy wariantów możliwych teamów nie rozsypywały tabelki.

Dodać opcję sterującą tym skracaniem: wartość `0` wyłącza skracanie, wartość `> 0` określa liczbę znaków.

**Comment by michzimny** [comment]
Super. Będzie jakiś PR? Czy dopiero po testach? :)

**Comment by emkael** [comment]
Szykuję sporą aktualizację, trochę funkcjonalności i poprawek się nazbierało.
