### ISSUE TITLE
Zbędne pole id w matches?

### ISSUE THREAD

**Issue by michzimny** [emkael/jfrteamy-playoff#5]
Czy identyfikatorów meczów nie mógłby program nadawać sobie wewnętrzne, żeby operator nie musiał ich ręcznie ustawiać w configu i nie narażał się na pomyłkę?

**Comment by emkael** [comment]
Ale to operator definiuje powiązania między meczami ("przegrany z meczu X", "wygrany w meczu Y" itd.), więc musi mieć jakiś sposób na zidentyfikowanie konkretnego meczu.

**Comment by michzimny** [comment]
Słusznie :)
